name: Salesforce Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Salesforce CLI
      run: npm install --global sfdx-cli
    
    - name: Authenticate to Salesforce
      run: |
        echo "${{ secrets.SF_JWT_KEY }}" > server.key
        sfdx force:auth:jwt:grant \
          --clientid ${{ secrets.SF_CLIENT_ID }} \
          --jwtkeyfile server.key \
          --username ${{ secrets.SF_USERNAME }} \
          --instanceurl ${{ secrets.SF_INSTANCE_URL }} \
          --setdefaultdevhubusername

    - name: Deploy to Salesforce (Validation Only)
      run: |
        sfdx force:source:deploy -p force-app -u ${{ secrets.SF_USERNAME }} --checkonly --json

